import { useEffect, useMemo, useRef, useState } from "react";
import { getRedirectResult, onAuthStateChanged, signInWithPopup, signInWithRedirect, signOut, type User } from "firebase/auth";
import { ImagePlus, LogOut, Search, UserRound, X, Moon, Sun, Play } from "lucide-react";
import { auth, authPersistence, googleProvider } from "~/lib/firebase";
import type { Route } from "./+types/home";

type Media = { key: string; size: number; uploaded: string; type: string; name: string };
type PickedFile = { file: File; url: string };
export async function loader() { return { storage: "Private media library" }; }
export function meta() { return [{ title: "muse — collect what moves you" }, { name: "description", content: "A private visual collection for your uploaded photos and videos." }]; }
const topics = ["All", "Inspiration", "Photography", "Art", "Nature", "Design"];

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [user, setUser] = useState<User | null>(null), [media, setMedia] = useState<Media[]>([]), [files, setFiles] = useState<PickedFile[]>([]), [topic, setTopic] = useState("All"), [search, setSearch] = useState(""), [message, setMessage] = useState(""), [uploading, setUploading] = useState(false), [night, setNight] = useState(false), [username, setUsername] = useState(""), [usernameDraft, setUsernameDraft] = useState(""), [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { let active = true; let unsubscribe = () => {}; void (async () => { try { await authPersistence; if (!active) return; unsubscribe = onAuthStateChanged(auth, nextUser => { if (active) { setUser(nextUser); if (nextUser) void loadMedia(nextUser); } }); const result = await getRedirectResult(auth); if (active && result?.user) setUser(result.user); } catch (e) { if (active) setMessage(e instanceof Error ? e.message : "Google sign-in failed."); } })(); return () => { active = false; unsubscribe(); }; }, []);
  async function loadMedia(current = user) { if (!current) return; const token = await current.getIdToken(); const response = await fetch("/api/media", { headers: { Authorization: `Bearer ${token}` } }); if (response.ok) { const body = await response.json() as { items: Media[] }; setMedia(body.items); } }
  const visible = useMemo(() => media.filter(item => item.name.toLowerCase().includes(search.toLowerCase())), [media, search]);
  const totalSize = useMemo(() => files.reduce((sum, item) => sum + item.file.size, 0), [files]);
  const formatSize = (bytes: number) => bytes > 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;
  async function login() { setMessage("Opening secure Google sign-in…"); try { const result = await signInWithPopup(auth, googleProvider); setUser(result.user); setMessage("Welcome to muse."); void loadMedia(result.user); } catch (e) { const code = e && typeof e === "object" && "code" in e ? String((e as { code?: unknown }).code) : ""; if (code === "auth/popup-blocked" || code === "auth/operation-not-supported-in-this-environment") { await signInWithRedirect(auth, googleProvider); return; } setMessage(code ? `Google sign-in error (${code}).` : "Google sign-in failed. Please try again."); } }
  async function logout() { await signOut(auth); setMedia([]); setUsername(""); setMessage("Signed out."); setMenuOpen(false); }
  function saveUsername() { const next = usernameDraft.trim().replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 24); if (next.length < 3) return setMessage("Choose a username with at least 3 letters or numbers."); setUsername(next); setUsernameDraft(""); setMessage(`@${next} is ready.`); }
  function addFiles(list: FileList | null) { if (!user || !username) { setMessage(user ? "Choose a username before uploading." : "Sign in with Google to upload."); return; } const incoming = Array.from(list ?? []).filter(file => /^(image|video)\//.test(file.type) && file.size > 0 && file.size <= 50 * 1024 * 1024); if (!incoming.length) return setMessage("Choose an image or video under 50 MB."); setFiles(current => [...current, ...incoming.map(file => ({ file, url: URL.createObjectURL(file) }))]); }
  async function upload() { if (!user || !username || !files.length) return setMessage("Choose a photo or video first."); setUploading(true); setMessage("Saving your collection…"); try { const token = await user.getIdToken(); for (const item of files) { const form = new FormData(); form.append("file", item.file, item.file.name || "upload"); const response = await fetch("/api/upload", { method: "POST", body: form, headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(((await response.json()) as { error?: string }).error ?? "Upload failed."); } files.forEach(item => URL.revokeObjectURL(item.url)); setFiles([]); await loadMedia(user); setMessage("Added to your collection."); } catch (e) { setMessage(e instanceof Error ? e.message : "Upload failed."); } finally { setUploading(false); } }
  return <main className={`muse ${night ? "dark" : ""}`}>
    <header className="topbar"><div className="wordmark"><span className="mark">m</span><span>muse</span></div><div className="search"><Search size={18} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your collection" /></div><button className="icon-button" onClick={() => setNight(v => !v)} aria-label="Toggle dark mode">{night ? <Sun size={19} /> : <Moon size={19} />}</button><button className="avatar" onClick={() => setMenuOpen(v => !v)} aria-label="Account">{user?.photoURL ? <img src={user.photoURL} alt="" /> : <UserRound size={18} />}</button>{menuOpen && <div className="account-menu">{user ? <><strong>{user.displayName ?? "Your account"}</strong><span>{username ? `@${username}` : "No username yet"}</span><button onClick={logout}><LogOut size={15} /> Sign out</button></> : <button onClick={login}>Continue with Google</button>}</div>}</header>
    <nav className="filters">{topics.map(item => <button key={item} className={topic === item ? "active" : ""} onClick={() => setTopic(item)}>{item}</button>)}</nav>
    <section className="intro"><div><p className="kicker">A place for your visual world</p><h1>Collect what<br /><i>moves you.</i></h1><p className="subcopy">Save the images and moments that make you pause.</p></div><button className="add-button" onClick={() => user ? inputRef.current?.click() : login()}><ImagePlus size={18} /> {user ? "Add to collection" : "Sign in to add"}</button><input ref={inputRef} type="file" multiple accept="image/*,video/*" className="hidden" onChange={e => { addFiles(e.currentTarget.files); e.currentTarget.value = ""; }} /></section>
    {user && !username && <section className="username-card"><strong>Make it yours</strong><span>Choose a username to start adding to your collection.</span><div><input value={usernameDraft} onChange={e => setUsernameDraft(e.target.value)} placeholder="your-username" aria-label="Username" maxLength={24} onKeyDown={e => e.key === "Enter" && saveUsername()} /><button onClick={saveUsername}>Continue</button></div></section>}
    {files.length > 0 && <section className="upload-drawer"><div><strong>{files.length} ready to save</strong><span>{formatSize(totalSize)} · private to you</span></div><button className="save-button" onClick={upload} disabled={uploading}>{uploading ? "Saving…" : "Save"}</button><button className="clear" onClick={() => setFiles([])} aria-label="Clear"><X size={18} /></button><div className="selected-grid">{files.map((item, index) => <div className="selected-thumb" key={item.url}><img src={item.url} alt={item.file.name} /><button onClick={() => setFiles(current => current.filter((_, i) => i !== index))}><X size={13} /></button></div>)}</div></section>}
    {message && <p className="message">{message}</p>}
    {visible.length ? <section className="masonry">{visible.map(item => <article className="pin" key={item.key}><div className="media-frame">{item.type.startsWith("video/") ? <><video src={`/api/media/${encodeURIComponent(item.key)}`} controls preload="metadata" /><span className="video-badge"><Play size={12} fill="currentColor" /></span></> : <img src={`/api/media/${encodeURIComponent(item.key)}`} alt={item.name} loading="lazy" />}</div><div className="pin-meta"><strong>{item.name}</strong><span>{new Date(item.uploaded).toLocaleDateString()}</span></div></article>)}</section> : <section className="empty"><ImagePlus size={28} /><h2>Your collection starts here.</h2><p>Upload your first photo or video to make this space yours.</p></section>}
    <footer>your private visual collection</footer>
  </main>;
}
